// demo/angular/src/app/voice_widget.component.ts
import { Component, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';

import { PicovoiceService } from '@picovoice/picovoice-angular';
import { PorcupineDetection, RhinoInference } from '@picovoice/picovoice-web';

@Component({
  selector: 'app-voice-widget',
  templateUrl: './voice_widget.component.html',
  styleUrls: ['./voice_widget.component.scss'],
})
export class VoiceWidget implements OnDestroy {
  isLoaded = false;
  isListening = false;
  contextInfo: string | null = null;
  error: string | null = null;
  wakeWordDetection: PorcupineDetection | null = null;
  inference: RhinoInference | null = null;
  private wakeWordDetectionSubscription: Subscription;
  private inferenceSubscription: Subscription;
  private contextInfoSubscription: Subscription;
  private isLoadedSubscription: Subscription;
  private isListeningSubscription: Subscription;
  private errorSubscription: Subscription;

  constructor(private picovoiceService: PicovoiceService) {
    this.wakeWordDetectionSubscription = picovoiceService.wakeWordDetection$.subscribe(
      (wakeWordDetection: PorcupineDetection) => {
        this.inference = null;
        this.wakeWordDetection = wakeWordDetection;
      }
    );

    this.inferenceSubscription = picovoiceService.inference$.subscribe(
      (inference: RhinoInference) => {
        this.wakeWordDetection = null;
        this.inference = inference;
      }
    );

    this.contextInfoSubscription = picovoiceService.contextInfo$.subscribe(
      (contextInfo: string | null) => {
        this.contextInfo = contextInfo;
      }
    );

    this.isLoadedSubscription = picovoiceService.isLoaded$.subscribe(
      (isLoaded: boolean) => {
        this.isLoaded = isLoaded;
      }
    );
    this.isListeningSubscription = picovoiceService.isListening$.subscribe(
      (isListening: boolean) => {
        this.isListening = isListening;
      }
    );
    this.errorSubscription = picovoiceService.error$.subscribe(
      (error: string | null) => {
        this.error = error;
      }
    );
  }
  ngOnDestroy(): void {
    this.wakeWordDetectionSubscription.unsubscribe();
    this.inferenceSubscription.unsubscribe();
    this.contextInfoSubscription.unsubscribe();
    this.isLoadedSubscription.unsubscribe();
    this.isListeningSubscription.unsubscribe();
    this.errorSubscription.unsubscribe();
    this.picovoiceService.release();
  }

  public async stop(): Promise<void> {
    await this.picovoiceService.stop();
  }

  public async start(): Promise<void> {
    await this.picovoiceService.start();
  }

  public async initEngine(accessKey: string): Promise<void> {
    if (accessKey.length >= 0) {
      await this.picovoiceService.init(
        accessKey,
        {
          label: 'Picovoice',
          publicPath: 'assets/picovoice_wasm.ppn',
          forceWrite: true,
        },
        { publicPath: 'assets/porcupine_params.pv', forceWrite: true },
        { publicPath: 'assets/clock_wasm.rhn', forceWrite: true },
        { publicPath: 'assets/rhino_params.pv', forceWrite: true }
      );
      try {
      } catch (error) {
        this.error = error;
      }
    }
  }

  public async release(): Promise<void> {
    await this.picovoiceService.release();
  }
}

<div class="voice-widget">
  <h1>VoiceWidget</h1>
  <h3>
    <label>
      AccessKey obtained from
      <a href="https://picovoice.ai/console/">Picovoice Console</a>:
      <input
        #accessKey
        [disabled]="isLoaded"
        name="accessKey"
        type="text"
      />
    </label>
    <button (click)="initEngine(accessKey.value)" [disabled]="isLoaded" class="start-button">
      Start Picovoice
    </button>
  </h3>
  <h3>Picovoice Loaded: {{ isLoaded }}</h3>
  <h3>Listening: {{ isListening }}</h3>
  <h3>Error: {{ error !== null }}</h3>
  <p *ngIf="error !== null" class="error-message">{{ error.toString() }}</p>

  <br />
  <button (click)="start()" [disabled]="error || !isLoaded || isListening">Start</button>
  <button (click)="stop()" [disabled]="error || !isLoaded || !isListening">Stop</button>
  <button (click)="release()" [disabled]="error || !isLoaded || isListening">Release</button>

  <div *ngIf="isListening">
    <h3 *ngIf="wakeWordDetection === null">Listening for 'Picovoice'...</h3>
    <h3 *ngIf="wakeWordDetection !== null">Wake word detected!</h3>
  </div>
  <div *ngIf="isListening && inference !== null">
    <h3>Inference:</h3>
    <pre>{{ inference | json }}</pre>
  </div>
  <hr />
  <h3>Context info</h3>
  <pre>{{ contextInfo }}</pre>
</div>

// demo/react/src/VoiceWidget.tsx
import { useState } from "react";
import { usePicovoice } from "@picovoice/picovoice-react";
import {
  PorcupineKeyword,
  PorcupineModel,
  RhinoContext,
  RhinoModel,
} from "@picovoice/picovoice-web";

export default function VoiceWidget() {
  const [inputValue, setInputValue] = useState("");

  const porcupineKeyword: PorcupineKeyword = {
    label: "picovoice",
    publicPath: "picovoice_wasm.ppn",
  };

  const porcupineModel: PorcupineModel = {
    publicPath: "porcupine_params.pv",
  };

  const rhinoContext: RhinoContext = {
    publicPath: "clock_wasm.rhn",
  };

  const rhinoModel: RhinoModel = {
    publicPath: "rhino_params.pv",
  };

  const {
    wakeWordDetection,
    inference,
    contextInfo,
    isLoaded,
    isListening,
    error,
    init,
    start,
    stop,
    release,
  } = usePicovoice();

  return (
    <div className="voice-widget">
      <h2>VoiceWidget</h2>
      <h3>
        <label>
          AccessKey obtained from{" "}
          <a href="https://console.picovoice.ai/">Picovoice Console</a>:
          <input
            type="text"
            name="accessKey"
            onChange={(value) => setInputValue(value.target.value)}
          />
        </label>
        <button
          className="start-button"
          onClick={async () =>
            await init(
              inputValue,
              porcupineKeyword,
              porcupineModel,
              rhinoContext,
              rhinoModel
            )
          }
        >
          Init Picovoice
        </button>
      </h3>
      <h3>Picovoice Loaded: {JSON.stringify(isLoaded)}</h3>
      <h3>Listening: {JSON.stringify(isListening)}</h3>
      <h3>Error: {JSON.stringify(error !== null)}</h3>
      {error !== null && (
        <p className="error-message">{JSON.stringify(error)}</p>
      )}
      <br />
      <button
        onClick={async () => await start()}
        disabled={error !== null || !isLoaded || isListening}
      >
        Start
      </button>
      <button
        onClick={async () => await stop()}
        disabled={error !== null || !isLoaded || !isListening}
      >
        Stop
      </button>

      <button
        onClick={async () => await release()}
        disabled={error !== null || !isLoaded || isListening}
      >
        Release
      </button>

      {isListening && (
        <>
          {wakeWordDetection ? (
            <h3>Wake word detected!</h3>
          ) : (
            <h3>Listening for the wake word 'Picovoice'...</h3>
          )}
        </>
      )}
      {isListening && inference && (
        <>
          <h3>Inference:</h3>
          <pre>{JSON.stringify(inference, null, 2)}</pre>
        </>
      )}
      <hr />
      <h3>Context info</h3>
      <pre>{contextInfo}</pre>
    </div>
  );
}
