// demo/react/src/App.jsx
import "./App.css";
import { useState } from "react";

import VoiceWidget from "./VoiceWidget";

function App() {
  const [show, setShow] = useState(true);
  return (
    <div className="App">
      <h1>Picovoice SDK for Web + React Hook ("usePicovoice" from @picovoice/picovoice-web-react)</h1>
      <button onClick={() => setShow(!show)}>
        Toggle VoiceWidget {show ? "OFF" : "ON"}
      </button>
      <br />
      <br />
      {show && <VoiceWidget />}
    </div>
  );
}

export default App;

// demo/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'picovoice-angular-demo-picovoice';
}

<style></style>
<h1>Picovoice Web + Angular</h1>
<button (click)="toggle()">Toggle VoiceWidget {{ show ? "OFF" : "ON" }}</button>
<br />
<br />

<voice-widget *ngIf="show"></voice-widget>
