// demo/react/src/VoiceWidget.jsx
import { useState, useEffect } from "react";
import { usePicovoice } from "@picovoice/picovoice-web-react";

const RHN_ALARM_CLOCK_64 =
  "cmhpbm8xLjYuMNEaAAAJAAAAcGljb3ZvaWNl//////////+UMAAAAGNvbnRleHQ6CiAgZXhwcmVzc2lvbnM6CiAgICB0aW1lcjoKICAgICAgLSAkdGltZXJBY3Rpb246YWN0aW9uIHRpbWVyCiAgICBzdG9wd2F0Y2g6CiAgICAgIC0gJHN0b3B3YXRjaEFjdGlvbjphY3Rpb24gc3RvcHdhdGNoCiAgICBjbG9jazoKICAgICAgLSAkY2xvY2tBY3Rpb246YWN0aW9uIChtZSkgKHRoZSkgY2xvY2sKICAgICAgLSAkY2xvY2tBY3Rpb246YWN0aW9uIChtZSkgKHRoZSkgdGltZQogICAgc2V0VGltZXI6CiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICBzZXRBbGFybToKICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VyICRwdi5Ud29EaWdpdEludGVnZXI6bWludXRlCiAgICAgICAgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkZGF5OmRheSAoYXQpICRwdi5Ud29EaWdpdEludGVnZXI6aG91cgogICAgICAgICRwdi5Ud29EaWdpdEludGVnZXI6bWludXRlICRhbVBtOmFtUG0KICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJGRheTpkYXkgKGF0KSAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGUKICAgICAgICAkYW1QbTphbVBtIChvbikgJGRheTpkYXkKICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VyICRhbVBtOmFtUG0gKG9uKSAkZGF5OmRheQogICAgYWxhcm06CiAgICAgIC0gJGFsYXJtQWN0aW9uOmFjdGlvbiBhbGFybQogICAgYXZhaWxhYmxlQ29tbWFuZHM6CiAgICAgIC0gd2hhdCBjYW4gSSBzYXkKICBzbG90czoKICAgIHRpbWVyQWN0aW9uOgogICAgICAtIHN0YXJ0CiAgICAgIC0gcGF1c2UKICAgICAgLSBzdG9wCiAgICAgIC0gcmVzZXQKICAgICAgLSBzaG93CiAgICAgIC0gcmVzdGFydAogICAgICAtIGNsZWFyCiAgICBjbG9ja0FjdGlvbjoKICAgICAgLSBzaG93CiAgICBzdG9wd2F0Y2hBY3Rpb246CiAgICAgIC0gc3RhcnQKICAgICAgLSBzdG9wCiAgICAgIC0gcGF1c2UKICAgICAgLSByZXNldAogICAgICAtIHJlc3RhcnQKICAgICAgLSBzaG93CiAgICBhbVBtOgogICAgICAtIGEgbQogICAgICAtIHAgbQogICAgZGF5OgogICAgICAtIHRvZGF5CiAgICAgIC0gdG9tb3Jyb3cKICAgICAgLSBtb25kYXkKICAgICAgLSB0dWVzZGF5CiAgICAgIC0gd2VkbmVzZGF5CiAgICAgIC0gdGh1cnNkYXkKICAgICAgLSBmcmlkYXkKICAgICAgLSBzYXR1cmRheQogICAgICAtIHN1bmRheQogICAgYWxhcm1BY3Rpb246CiAgICAgIC0gZGVsZXRlCgAAjwAAAAAAAAACAAAABgAAAAwAAAAPAAAAEwAAABYAAAAaAAAAIAAAACYAAAAtAAAAMwAAADwAAABDAAAAUAAAAFwAAABoAAAAdAAAAH8AAACMAAAAlwAAAKQAAACvAAAAtgAAAL4AAADEAAAA0AAAANsAAADmAAAA8QAAAPsAAAAHAQAAEQEAAB0BAAAnAQAALAEAADABAAA2AQAAQgEAAE0BAABYAQAAYwEAAG0BAAB5AQAAgwEAAI8BAACZAQAAngEAAKcBAACuAQAAswEAALkBAAC7AQAAvgEAAMUBAADNAQAA1AEAANkBAADiAQAA6QEAAPYBAAACAgAADgIAABoCAAAlAgAAMgIAAD0CAABKAgAAVQIAAFgCAABcAgAAYAIAAGYCAABsAgAAdAIAAH0CAACBAgAAiAIAAJACAACUAgAAmgIAAKQCAACsAgAAugIAAMcCAADUAgAA4QIAAO0CAAD7AgAABwMAABUDAAAhAwAAJgMAACoDAAAyAwAAOAMAAEQDAABPAwAAWgMAAGUDAABvAwAAewMAAIUDAACRAwAAmwMAAKEDAACmAwAAsAMAALcDAAC7AwAAvwMAAMgDAADPAwAA3AMAAOgDAAD0AwAAAAQAAAsEAAAYBAAAIwQAADAEAAA7BAAAQQQAAEoEAABPBAAAVQQAAFsEAABkBAAAbAQAAHMEAAB6BAAAhwQAAJMEAACfBAAAqwQAALYEAADDBAAAzgQAANsEAADmBAAA6gQAAPQEAAD5BAAA/gQAAGEAYSBtAGFsYXJtAGFuAGFuZABhdABjYW4AY2xlYXIAY2xvY2sAZGVsZXRlAGVpZ2h0AGVpZ2h0ZWVuAGVpZ2h0eQBlaWdodHkgZWlnaHQAZWlnaHR5IGZpdmUAZWlnaHR5IGZvdXIAZWlnaHR5IG5pbmUAZWlnaHR5IG9uZQBlaWdodHkgc2V2ZW4AZWlnaHR5IHNpeABlaWdodHkgdGhyZWUAZWlnaHR5IHR3bwBlbGV2ZW4AZmlmdGVlbgBmaWZ0eQBmaWZ0eSBlaWdodABmaWZ0eSBmaXZlAGZpZnR5IGZvdXIAZmlmdHkgbmluZQBmaWZ0eSBvbmUAZmlmdHkgc2V2ZW4AZmlmdHkgc2l4AGZpZnR5IHRocmVlAGZpZnR5IHR3bwBmaXZlAGZvcgBmb3J0eQBmb3J0eSBlaWdodABmb3J0eSBmaXZlAGZvcnR5IGZvdXIAZm9ydHkgbmluZQBmb3J0eSBvbmUAZm9ydHkgc2V2ZW4AZm9ydHkgc2l4AGZvcnR5IHRocmVlAGZvcnR5IHR3bwBmb3VyAGZvdXJ0ZWVuAGZyaWRheQBob3VyAGhvdXJzAGkAbWUAbWludXRlAG1pbnV0ZXMAbW9uZGF5AG5pbmUAbmluZXRlZW4AbmluZXR5AG5pbmV0eSBlaWdodABuaW5ldHkgZml2ZQBuaW5ldHkgZm91cgBuaW5ldHkgbmluZQBuaW5ldHkgb25lAG5pbmV0eSBzZXZlbgBuaW5ldHkgc2l4AG5pbmV0eSB0aHJlZQBuaW5ldHkgdHdvAG9uAG9uZQBwIG0AcGF1c2UAcmVzZXQAcmVzdGFydABzYXR1cmRheQBzYXkAc2Vjb25kAHNlY29uZHMAc2V0AHNldmVuAHNldmVudGVlbgBzZXZlbnR5AHNldmVudHkgZWlnaHQAc2V2ZW50eSBmaXZlAHNldmVudHkgZm91cgBzZXZlbnR5IG5pbmUAc2V2ZW50eSBvbmUAc2V2ZW50eSBzZXZlbgBzZXZlbnR5IHNpeABzZXZlbnR5IHRocmVlAHNldmVudHkgdHdvAHNob3cAc2l4AHNpeHRlZW4Ac2l4dHkAc2l4dHkgZWlnaHQAc2l4dHkgZml2ZQBzaXh0eSBmb3VyAHNpeHR5IG5pbmUAc2l4dHkgb25lAHNpeHR5IHNldmVuAHNpeHR5IHNpeABzaXh0eSB0aHJlZQBzaXh0eSB0d28Ac3RhcnQAc3RvcABzdG9wd2F0Y2gAc3VuZGF5AHRlbgB0aGUAdGhpcnRlZW4AdGhpcnR5AHRoaXJ0eSBlaWdodAB0aGlydHkgZml2ZQB0aGlydHkgZm91cgB0aGlydHkgbmluZQB0aGlydHkgb25lAHRoaXJ0eSBzZXZlbgB0aGlydHkgc2l4AHRoaXJ0eSB0aHJlZQB0aGlydHkgdHdvAHRocmVlAHRodXJzZGF5AHRpbWUAdGltZXIAdG9kYXkAdG9tb3Jyb3cAdHVlc2RheQB0d2VsdmUAdHdlbnR5AHR3ZW50eSBlaWdodAB0d2VudHkgZml2ZQB0d2VudHkgZm91cgB0d2VudHkgbmluZQB0d2VudHkgb25lAHR3ZW50eSBzZXZlbgB0d2VudHkgc2l4AHR3ZW50eSB0aHJlZQB0d2VudHkgdHdvAHR3bwB3ZWRuZXNkYXkAd2hhdAB6ZXJvAAAAAAAAAAIAAAAEAAAABQAAAAcAAAAJAAAACgAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAGAAAABkAAAAaAAAAGwAAABwAAAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAAJgAAACcAAAAoAAAAKQAAACoAAAArAAAALgAAAC8AAAAwAAAAMQAAADIAAAAzAAAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAAOwAAAD0AAAA/AAAAQQAAAEIAAABDAAAARgAAAEcAAABJAAAASgAAAEsAAABMAAAATQAAAE4AAABPAAAAUAAAAFIAAABTAAAAVAAAAFUAAABWAAAAWAAAAFoAAABbAAAAXAAAAF0AAABeAAAAYAAAAGEAAABjAAAAZQAAAGYAAABnAAAAaAAAAGoAAABsAAAAbgAAAHAAAAByAAAAdgAAAHgAAAB6AAAAfAAAAH4AAAB/AAAAgAAAAIEAAACCAAAAgwAAAIQAAACFAAAAhgAAAIgAAACJAAAAigAAAIsAAACMAAAAjQAAAI4AAACPAAAAkQAAAJIAAACUAAAAlQAAAJcAAACZAAAAmwAAAJ0AAACfAAAAowAAAKUAAACnAAAAqQAAAKsAAACsAAAArgAAAK8AAACwAAAAsgAAALQAAAC3AAAAuAAAALoAAAC8AAAAvgAAAMAAAADCAAAAxgAAAMgAAADKAAAAzAAAAM4AAADPAAAA0QAAANMAAADVAAAAAAAAAAEAAAACAAAABQAAAAgAAAANAAAADwAAABEAAAAUAAAAFwAAABkAAAAcAAAAHwAAACMAAAAnAAAALAAAAC4AAAAyAAAANQAAADoAAABAAAAARgAAAEwAAABSAAAAWQAAAGEAAABoAAAAbgAAAHMAAAB5AAAAfwAAAIUAAACKAAAAkQAAAJkAAAChAAAAqQAAALEAAAC6AAAAxAAAAM0AAADVAAAA3AAAAN8AAADiAAAA5AAAAOcAAADsAAAA8wAAAPsAAAADAQAACwEAABMBAAAcAQAAJgEAAC8BAAA3AQAAPgEAAEEBAABHAQAATAEAAFEBAABTAQAAVQEAAFgBAABbAQAAXAEAAF4BAABjAQAAaAEAAG4BAAB0AQAAeQEAAH4BAACBAQAAhwEAAIwBAACTAQAAmwEAAKMBAACrAQAAswEAALwBAADGAQAAzwEAANcBAADeAQAA4AEAAOIBAADlAQAA6QEAAO0BAADwAQAA9QEAAPwBAAACAgAACAIAAAoCAAAQAgAAFQIAABwCAAAiAgAAJQIAACoCAAAyAgAAOQIAAD8CAABIAgAAUAIAAFoCAABjAgAAbQIAAHYCAACAAgAAiQIAAJMCAACeAgAApwIAALECAAC9AgAAyAIAANMCAADdAgAA5wIAAPACAAD5AgAAAQMAAAMDAAAHAwAADgMAABQDAAAcAwAAJQMAAC4DAAA3AwAAQAMAAEoDAABVAwAAXwMAAGgDAABwAwAAdQMAAHkDAACAAwAAhQMAAIoDAACNAwAAjwMAAJEDAACWAwAAmgMAAJ4DAACkAwAAqgMAALEDAAC4AwAAvwMAAMYDAADNAwAA1AMAANsDAADjAwAA6gMAAPIDAAD7AwAABAQAAAwEAAAUBAAAGwQAACIEAAAoBAAALgQAADEEAAA2BAAAOwQAAD4EAABCBAAARgQAAEoEAABQBAAAVgQAAFsEAABgBAAAZgQAAGsEAABxBAAAdgQAAH4EAACFBAAAjgQAAJYEAACfBAAApwQAALAEAAC4BAAAwQQAAMsEAADTBAAA3AQAAOcEAADxBAAA+wQAAAQFAAANBQAAFQUAAB0FAAAkBQAAJgUAACwFAAAyBQAANQUAADkFAAA9BQAAQQUAAAMNAwsWDQsWAxUBHBYCFwMXAxcJAhcJAh8UAhcUAxcUFREcFBUBFAkRFRIfDR8NHxIXDR8SDR8SDR8NHxIOBiMNHxIOBBwNHxIXBhcNHxIkAxcNHxIQJAMXDR8SHQsjAxcNHxIdERQdDR8SIBwSDR8SHyIRFQsjAxcSFQsjAxcOEQ4fEhcOEQ4fEg4RDh8SDR8OEQ4fEg4GIw4RDh8SDgQcDhEOHxIXBhcOEQ4fEiQDFw4RDh8SECQDFw4RDh8SHQsjAxcOEQ4fEh0RFB0OEQ4fEiAcEg4RDh8SHyIOBiMOBBwODA4cDA4EHB8SDgQcHxINHw4EHB8SDgYjDgQcHxIOBBwOBBwfEhcGFw4EHB8SJAMXDgQcHxIQJAMXDgQcHxIdCyMDFw4EHB8SHREUHQ4EHB8SIBwSDgQcHxIfIg4EHA4EHB8SFw4cBgkSDhwGCQ0FDAUcBQwmBRwmBhYSFhEXAx8WBhciHxYGFyUiHxYRFwMfHRYDFwkSFgMXCQ0XBhcXBhcfEhcXBhcfEhcGFx8SDR8XBhcfEg4GIxcGFx8SDgQcFwYXHxIXBhcXBhcfEiQDFxcGFx8SECQDFxcGFx8SHQsjAxcXBhcfEh0RFB0XBhcfEiAcEhcGFx8SHyIBFwQXJAMXECQDFxsSCxYbBCYcEh0LHxwSHR8BHB8dAh8MCRIdAh8RCQ0dDR0LFAMXCR0LFAMXHQsUAxcJJh0LFAMXJh0LHx0LIwMXHQsjAxcfEhcdCyMDFx8SHQsjAxcSHQsjAxcfEg0fHQsjAxcSDR8dCyMDFx8SDgYjHQsjAxcSDgYjHQsjAxcfEg4EHB0LIwMXEg4EHB0LIwMXHxIXBhcdCyMDFxIXBhcdCyMDFx8SJAMXHQsjAxcfEhAkAxcdCyMDFxIkAxcdCyMDFxIQJAMXHQsjAxcfEh0LIwMXHQsjAxcSHQsjAxcdCyMDFx8SHREUHR0LIwMXEh0RFB0dCyMDFx8SIBwSHQsjAxcSIBwSHQsjAxcfEh8iHQsjAxcSHyIeGR0RFB0dERQdHxIXHREUHR8SHREUHR8SDR8dERQdHxIOBiMdERQdHxIOBBwdERQdHxIXBhcdERQdHxIkAxcdERQdHxIQJAMXHREUHR8SHQsjAxcdERQdHxIdERQdHREUHR8SIBwSHREUHR8SHyIdHwEcHx0fARsdHwEbJAEIHQMXCQ0dAxcJEh8LFwoDChIgDB8SFyAMCRIgDB8SIAwJEg0fIAwfEg0fIAwJEg4GIyAMHxIOBiMgDAkSDgQcIAwfEg4EHCAMCRIXBhcgDB8SFwYXIAwJEiQDFyAMCRIQJAMXIAwfEiQDFyAMHxIQJAMXIAwJEh0LIwMXIAwfEh0LIwMXIAwJEh0RFB0gDB8SHREUHSAMCRIgHBIgDB8SIBwSIAwJEh8iIAwfEh8iIBwSIAwmCQ0gDCYJEh8GFh8GFgwfAwkNHyIJDR8DFgEcGR8iFgEcGR8iJgkSHyImCQ0fJSImCQ0fJAsVIx8kCxcfEh8kCxcSHyQLFx8SDR8fJAsXEg0fHyQLFx8SDgYjHyQLFxIOBiMfJAsXHxIOBBwfJAsXEg4EHB8kCxcfEhcGFx8kCxcSFwYXHyQLFx8SJAMXHyQLFx8SECQDFx8kCxcSJAMXHyQLFxIQJAMXHyQLFx8SHQsjAxcfJAsXEh0LIwMXHyQLFx8SHREUHR8kCxcSHREUHR8kCxcfEiAcEh8kCxcSIBwSHyQLFx8SHyIfJAsXEh8iHyIkCxcmCRIkCxcmCQ0kAx8QJAMfJhEcGSYSHBkAAAAgAAAAAAAAAAEAAAADAAAABAAAAA0AAABxAAAA1QAAADkBAACdAQAAAQIAAAcCAAAOAgAAEAIAABICAAAUAgAAFQIAABYCAAAXAgAAGAIAABkCAAAaAgAAGwIAABwCAAAdAgAAHgIAAB8CAAAgAgAAIQIAACICAAAjAgAAJAIAACUCAAAmAgAACQAAAAEAAABGAAAAWwAAAH0AAAB+AAAANwAAAH8AAACMAAAAegAAADAAAABKAAAAawAAAI4AAABFAAAAiwAAAHkAAAAuAAAAIgAAAFwAAABPAAAACgAAADgAAABsAAAAFgAAAIAAAABuAAAALwAAABcAAABdAAAAUAAAAAsAAAA5AAAAgQAAAIYAAACKAAAAiQAAAIQAAACDAAAAiAAAAIcAAACCAAAAhQAAAG8AAAB0AAAAeAAAAHcAAAByAAAAcQAAAHYAAAB1AAAAcAAAAHMAAAAkAAAAKQAAAC0AAAAsAAAAJwAAACYAAAArAAAAKgAAACUAAAAoAAAAGAAAAB0AAAAhAAAAIAAAABsAAAAaAAAAHwAAAB4AAAAZAAAAHAAAAF4AAABjAAAAZwAAAGYAAABhAAAAYAAAAGUAAABkAAAAXwAAAGIAAABRAAAAVgAAAFoAAABZAAAAVAAAAFMAAABYAAAAVwAAAFIAAABVAAAADAAAABEAAAAVAAAAFAAAAA8AAAAOAAAAEwAAABIAAAANAAAAEAAAADoAAAA/AAAAQwAAAEIAAAA9AAAAPAAAAEEAAABAAAAAOwAAAD4AAACOAAAARQAAAIsAAAB5AAAALgAAACIAAABcAAAATwAAAAoAAAA4AAAAbAAAABYAAACAAAAAbgAAAC8AAAAXAAAAXQAAAFAAAAALAAAAOQAAAIEAAACGAAAAigAAAIkAAACEAAAAgwAAAIgAAACHAAAAggAAAIUAAABvAAAAdAAAAHgAAAB3AAAAcgAAAHEAAAB2AAAAdQAAAHAAAABzAAAAJAAAACkAAAAtAAAALAAAACcAAAAmAAAAKwAAACoAAAAlAAAAKAAAABgAAAAdAAAAIQAAACAAAAAbAAAAGgAAAB8AAAAeAAAAGQAAABwAAABeAAAAYwAAAGcAAABmAAAAYQAAAGAAAABlAAAAZAAAAF8AAABiAAAAUQAAAFYAAABaAAAAWQAAAFQAAABTAAAAWAAAAFcAAABSAAAAVQAAAAwAAAARAAAAFQAAABQAAAAPAAAADgAAABMAAAASAAAADQAAABAAAAA6AAAAPwAAAEMAAABCAAAAPQAAADwAAABBAAAAQAAAADsAAAA+AAAAjgAAAEUAAACLAAAAeQAAAC4AAAAiAAAAXAAAAE8AAAAKAAAAOAAAAGwAAAAWAAAAgAAAAG4AAAAvAAAAFwAAAF0AAABQAAAACwAAADkAAACBAAAAhgAAAIoAAACJAAAAhAAAAIMAAACIAAAAhwAAAIIAAACFAAAAbwAAAHQAAAB4AAAAdwAAAHIAAABxAAAAdgAAAHUAAABwAAAAcwAAACQAAAApAAAALQAAACwAAAAnAAAAJgAAACsAAAAqAAAAJQAAACgAAAAYAAAAHQAAACEAAAAgAAAAGwAAABoAAAAfAAAAHgAAABkAAAAcAAAAXgAAAGMAAABnAAAAZgAAAGEAAABgAAAAZQAAAGQAAABfAAAAYgAAAFEAAABWAAAAWgAAAFkAAABUAAAAUwAAAFgAAABXAAAAUgAAAFUAAAAMAAAAEQAAABUAAAAUAAAADwAAAA4AAAATAAAAEgAAAA0AAAAQAAAAOgAAAD8AAABDAAAAQgAAAD0AAAA8AAAAQQAAAEAAAAA7AAAAPgAAAI4AAABFAAAAiwAAAHkAAAAuAAAAIgAAAFwAAABPAAAACgAAADgAAABsAAAAFgAAAIAAAABuAAAALwAAABcAAABdAAAAUAAAAAsAAAA5AAAAgQAAAIYAAACKAAAAiQAAAIQAAACDAAAAiAAAAIcAAACCAAAAhQAAAG8AAAB0AAAAeAAAAHcAAAByAAAAcQAAAHYAAAB1AAAAcAAAAHMAAAAkAAAAKQAAAC0AAAAsAAAAJwAAACYAAAArAAAAKgAAACUAAAAoAAAAGAAAAB0AAAAhAAAAIAAAABsAAAAaAAAAHwAAAB4AAAAZAAAAHAAAAF4AAABjAAAAZwAAAGYAAABhAAAAYAAAAGUAAABkAAAAXwAAAGIAAABRAAAAVgAAAFoAAABZAAAAVAAAAFMAAABYAAAAVwAAAFIAAABVAAAADAAAABEAAAAVAAAAFAAAAA8AAAAOAAAAEwAAABIAAAANAAAAEAAAADoAAAA/AAAAQwAAAEIAAAA9AAAAPAAAAEEAAABAAAAAOwAAAD4AAACOAAAARQAAAIsAAAB5AAAALgAAACIAAABcAAAATwAAAAoAAAA4AAAAbAAAABYAAACAAAAAbgAAAC8AAAAXAAAAXQAAAFAAAAALAAAAOQAAAIEAAACGAAAAigAAAIkAAACEAAAAgwAAAIgAAACHAAAAggAAAIUAAABvAAAAdAAAAHgAAAB3AAAAcgAAAHEAAAB2AAAAdQAAAHAAAABzAAAAJAAAACkAAAAtAAAALAAAACcAAAAmAAAAKwAAACoAAAAlAAAAKAAAABgAAAAdAAAAIQAAACAAAAAbAAAAGgAAAB8AAAAeAAAAGQAAABwAAABeAAAAYwAAAGcAAABmAAAAYQAAAGAAAABlAAAAZAAAAF8AAABiAAAAUQAAAFYAAABaAAAAWQAAAFQAAABTAAAAWAAAAFcAAABSAAAAVQAAAAwAAAARAAAAFQAAABQAAAAPAAAADgAAABMAAAASAAAADQAAABAAAAA6AAAAPwAAAEMAAABCAAAAPQAAADwAAABBAAAAQAAAADsAAAA+AAAAaAAAAGkAAABHAAAASAAAAEkAAABbAAAAaAAAAEcAAABpAAAASAAAAFsAAABJAAAABwAAADEAAAAyAAAANQAAADYAAABMAAAATQAAAAAAAAACAAAAAwAAAAQAAAAFAAAABgAAAAgAAAAjAAAAMwAAADQAAABEAAAASwAAAE4AAABqAAAAbQAAAHsAAAB8AAAAjQAAAAAAAAAMAAAAEQAAAB0AAAAhAAAANAAAAEcAAABaAAAAbQAAAIAAAACQAAAAnAAAAJ0AAACeAAAAnwAAAKAAAAChAAAAogAAAKMAAACkAAAApQAAAKYAAACnAAAAqAAAAKkAAACqAAAAqwAAAKwAAACtAAAArgAAAK8AAACwAAAAsQAAAGFsYXJtQWN0aW9uAGFtUG0AY2xvY2tBY3Rpb24AZGF5AHB2LlR3b0RpZ2l0SW50ZWdlcgBwdi5Ud29EaWdpdEludGVnZXIAcHYuVHdvRGlnaXRJbnRlZ2VyAHB2LlR3b0RpZ2l0SW50ZWdlcgBwdi5Ud29EaWdpdEludGVnZXIAc3RvcHdhdGNoQWN0aW9uAHRpbWVyQWN0aW9uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAADAAAABMAAAAXAAAAHAAAACIAAAApAAAAMQAAADkAAABAAAAARwAAAEgAAABJAAAASgAAAEsAAABMAAAATQAAAE4AAABPAAAAUAAAAFEAAABSAAAAUwAAAFQAAABVAAAAVgAAAFcAAABYAAAAWQAAAFoAAABbAAAAXAAAAGFjdGlvbgBhbVBtAGFjdGlvbgBkYXkAaG91cgBob3VycwBtaW51dGUAbWludXRlcwBzZWNvbmRzAGFjdGlvbgBhY3Rpb24AAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAGAAAAGAAAAB4AAAAnAAAAMAAAADoAAABAAAAAYWxhcm0AYXZhaWxhYmxlQ29tbWFuZHMAY2xvY2sAc2V0QWxhcm0Ac2V0VGltZXIAc3RvcHdhdGNoAHRpbWVyAAQAAAAAAAAA//////////8GAAAAKAAAAEwAAABwAAAAXAEAAAQKAAAoCgAAAAAAAAoAAAD/////AQAAADwAAAAoAAAAHgAAAAYAAAAAAAAAAAAAAAkAAAD/////AQAAAGAAAABMAAAAGwAAAAUAAAAAAAAAAAAAAAIAAAD/////BAAAAJAAAAAEAQAAPAEAAEwBAABwAAAAFwAAAP////8DAAAArAAAAOQAAAD0AAAAkAAAABwAAAD/////AgAAAMQAAADUAAAArAAAABQAAAACAAAAAAAAAKwAAAAdAAAAAgAAAAAAAACQAAAAFAAAAAIAAAAAAAAAkAAAAB0AAAACAAAAAAAAAHAAAAAcAAAA/////wIAAAAcAQAALAEAAAQBAAAUAAAAAgAAAAAAAAAEAQAAHQAAAAIAAAAAAAAAcAAAABQAAAACAAAAAAAAAHAAAAAdAAAAAgAAAAAAAAAAAAAAGgAAAP////8EAAAAfAEAAAwEAACIBgAAUAgAAFwBAAAOAAAA/////wEAAACQAQAAfAEAAB4AAAD/////AQAAAKQBAACQAQAAFQAAAP////8DAAAAwAEAAGADAADoAwAApAEAAAUAAAD/////AQAAANQBAADAAQAACwAAAAQAAAADAAAA8AEAALQCAAA8AwAA1AEAABEAAAD/////AgAAAAgCAACQAgAA8AEAAAcAAAD/////AQAAABwCAAAIAgAADAAAAAQAAAACAAAANAIAAGwCAAAcAgAAEQAAAP////8BAAAASAIAADQCAAAIAAAA/////wEAAABcAgAASAIAAA0AAAAEAAAAAAAAABwCAAAIAAAA/////wEAAACAAgAAbAIAAA0AAAAEAAAAAAAAAPABAAAIAAAA/////wEAAACkAgAAkAIAAA0AAAAEAAAAAAAAANQBAAAHAAAA/////wEAAADIAgAAtAIAAAwAAAAEAAAAAgAAAOACAAAYAwAAyAIAABEAAAD/////AQAAAPQCAADgAgAACAAAAP////8BAAAACAMAAPQCAAANAAAABAAAAAAAAADIAgAACAAAAP////8BAAAALAMAABgDAAANAAAABAAAAAAAAADUAQAACAAAAP////8BAAAAUAMAADwDAAANAAAABAAAAAAAAACkAQAABwAAAP////8BAAAAdAMAAGADAAAMAAAABAAAAAIAAACMAwAAxAMAAHQDAAARAAAA/////wEAAACgAwAAjAMAAAgAAAD/////AQAAALQDAACgAwAADQAAAAQAAAAAAAAAdAMAAAgAAAD/////AQAAANgDAADEAwAADQAAAAQAAAAAAAAApAEAAAgAAAD/////AQAAAPwDAADoAwAADQAAAAQAAAAAAAAAXAEAAB4AAAD/////AQAAACAEAAAMBAAAFQAAAP////8DAAAAPAQAANwFAABkBgAAIAQAAAUAAAD/////AQAAAFAEAAA8BAAACwAAAAQAAAADAAAAbAQAADAFAAC4BQAAUAQAABEAAAD/////AgAAAIQEAAAMBQAAbAQAAAcAAAD/////AQAAAJgEAACEBAAADAAAAAQAAAACAAAAsAQAAOgEAACYBAAAEQAAAP////8BAAAAxAQAALAEAAAIAAAA/////wEAAADYBAAAxAQAAA0AAAAEAAAAAAAAAJgEAAAIAAAA/////wEAAAD8BAAA6AQAAA0AAAAEAAAAAAAAAGwEAAAIAAAA/////wEAAAAgBQAADAUAAA0AAAAEAAAAAAAAAFAEAAAHAAAA/////wEAAABEBQAAMAUAAAwAAAAEAAAAAgAAAFwFAACUBQAARAUAABEAAAD/////AQAAAHAFAABcBQAACAAAAP////8BAAAAhAUAAHAFAAANAAAABAAAAAAAAABEBQAACAAAAP////8BAAAAqAUAAJQFAAANAAAABAAAAAAAAABQBAAACAAAAP////8BAAAAzAUAALgFAAANAAAABAAAAAAAAAAgBAAABwAAAP////8BAAAA8AUAANwFAAAMAAAABAAAAAIAAAAIBgAAQAYAAPAFAAARAAAA/////wEAAAAcBgAACAYAAAgAAAD/////AQAAADAGAAAcBgAADQAAAAQAAAAAAAAA8AUAAAgAAAD/////AQAAAFQGAABABgAADQAAAAQAAAAAAAAAIAQAAAgAAAD/////AQAAAHgGAABkBgAADQAAAAQAAAAAAAAAXAEAABAAAAD/////AQAAAJwGAACIBgAADwAAAP////8BAAAAsAYAAJwGAAAVAAAA/////wIAAADIBgAAjAcAALAGAAAEAAAA/////wIAAADgBgAAQAcAAMgGAAAGAAAA/////wEAAAD0BgAA4AYAAAEAAAADAAAAAgAAAAwHAAAwBwAA9AYAABgAAAD/////AQAAACAHAAAMBwAAAwAAAAMAAAAAAAAA9AYAAAMAAAADAAAAAAAAAMgGAAABAAAAAwAAAAIAAABYBwAAfAcAAEAHAAAYAAAA/////wEAAABsBwAAWAcAAAMAAAADAAAAAAAAAEAHAAADAAAAAwAAAAAAAACwBgAAAwAAAP////8CAAAApAcAAAQIAACMBwAAEgAAAP////8BAAAAuAcAAKQHAAAEAAAA/////wIAAADQBwAA9AcAALgHAAAGAAAA/////wEAAADkBwAA0AcAAAEAAAADAAAAAAAAALgHAAABAAAAAwAAAAAAAACMBwAABAAAAP////8CAAAAHAgAAEAIAAAECAAABgAAAP////8BAAAAMAgAABwIAAABAAAAAwAAAAAAAAAECAAAAQAAAAMAAAAAAAAAXAEAAA8AAAD/////AQAAAGQIAABQCAAAFQAAAP////8CAAAAfAgAAEAJAABkCAAABAAAAP////8CAAAAlAgAAPQIAAB8CAAABgAAAP////8BAAAAqAgAAJQIAAABAAAAAwAAAAIAAADACAAA5AgAAKgIAAAYAAAA/////wEAAADUCAAAwAgAAAMAAAADAAAAAAAAAKgIAAADAAAAAwAAAAAAAAB8CAAAAQAAAAMAAAACAAAADAkAADAJAAD0CAAAGAAAAP////8BAAAAIAkAAAwJAAADAAAAAwAAAAAAAAD0CAAAAwAAAAMAAAAAAAAAZAgAAAMAAAD/////AgAAAFgJAAC4CQAAQAkAABIAAAD/////AQAAAGwJAABYCQAABAAAAP////8CAAAAhAkAAKgJAABsCQAABgAAAP////8BAAAAmAkAAIQJAAABAAAAAwAAAAAAAABsCQAAAQAAAAMAAAAAAAAAQAkAAAQAAAD/////AgAAANAJAAD0CQAAuAkAAAYAAAD/////AQAAAOQJAADQCQAAAQAAAAMAAAAAAAAAuAkAAAEAAAADAAAAAAAAAAAAAAAAAAAA/////wEAAAAYCgAABAoAAA8AAAAAAAAAAAAAAAAAAAAfAAAA/////wEAAAA8CgAAKAoAABMAAAD/////AQAAAFAKAAA8CgAAFgAAAP////8BAAAAZAoAAFAKAAAZAAAAAQAAAAAAAAA=";

export default function VoiceWidget() {
  const [isChunkLoaded, setIsChunkLoaded] = useState(false);
  const [workerChunk, setWorkerChunk] = useState({ workerFactory: null });

  useEffect(() => {
    async function loadPorcupineWorkerChunk() {
      const pvWorkerFactory = (
        await import("@picovoice/picovoice-web-en-worker")
      ).PicovoiceWorkerFactory; // <-- Dynamically import the worker
      console.log("Picovoice worker chunk is loaded.");
      return pvWorkerFactory;
    }
    if (workerChunk.workerFactory === null) {
      // <-- We only want to load once!
      loadPorcupineWorkerChunk().then((ppnWorkerFactory) => {
        setWorkerChunk({ workerFactory: ppnWorkerFactory });
        setIsChunkLoaded(true);
      });
    }
  }, [workerChunk]);

  const [keywordDetections, setKeywordDetections] = useState([]);
  const [inference, setInference] = useState(null);

  const inferenceEventHandler = (rhinoInference) => {
    console.log(rhinoInference);
    setInference(rhinoInference);
  };

  const keywordEventHandler = (porcupineKeywordLabel) => {
    console.log(porcupineKeywordLabel);
    setKeywordDetections((x) => [...x, porcupineKeywordLabel]);
    setInference("...");
  };

  const {
    contextInfo,
    isLoaded,
    isListening,
    isError,
    errorMessage,
    start,
    resume,
    pause,
    engine,
  } = usePicovoice(
    workerChunk.workerFactory, // <-- When this is null/undefined, it's ignored. Otherwise, usePicovoice will start.
    {
      porcupineKeyword: "Bumblebee",
      rhinoContext: { base64: RHN_ALARM_CLOCK_64 },
    },
    keywordEventHandler,
    inferenceEventHandler
  );

  return (
    <div className="voice-widget">
      <h2>VoiceWidget</h2>
      <h3>Dynamic Import Loaded: {JSON.stringify(isChunkLoaded)}</h3>
      <h3>Loaded: {JSON.stringify(isLoaded)}</h3>
      <h3>Listening: {JSON.stringify(isListening)}</h3>
      <h3>Error: {JSON.stringify(isError)}</h3>
      <h3>Engine: {JSON.stringify(engine)}</h3>
      {isError && (
        <p className="error-message">{JSON.stringify(errorMessage)}</p>
      )}
      <br />
      <button
        onClick={() => start()}
        disabled={!isLoaded || isListening || isError}
      >
        Start
      </button>
      <button
        onClick={() => pause()}
        disabled={!isLoaded || !isListening || isError}
      >
        Pause
      </button>
      <button
        onClick={() => resume()}
        disabled={!isLoaded || isListening || isError}
      >
        Resume
      </button>
      <h3>Keyword Detections (Listening for "Bumblebee"):</h3>
      {keywordDetections.length > 0 && (
        <ul>
          {keywordDetections.map((label, index) => (
            <li key={index}>{label}</li>
          ))}
        </ul>
      )}
      <h3>Inference:</h3>
      <pre>{JSON.stringify(inference, null, 2)}</pre>
      <br />
      <br />
      <br />
      <hr />
      <h2>Context info</h2>
      <pre>{contextInfo}</pre>
    </div>
  );
}

// demo/vue/src/components/VoiceWidget.vue
<template>
  <div class="voice-widget">
    <Picovoice
      ref="picovoice"
      v-bind:picovoiceFactoryArgs="{
        start: true,
        porcupineKeyword: 'Picovoice',
        rhinoContext: {
          base64:
            'cmhpbm8xLjYuMNEaAAAJAAAAcGljb3ZvaWNl//////////+UMAAAAGNvbnRleHQ6CiAgZXhwcmVzc2lvbnM6CiAgICB0aW1lcjoKICAgICAgLSAkdGltZXJBY3Rpb246YWN0aW9uIHRpbWVyCiAgICBzdG9wd2F0Y2g6CiAgICAgIC0gJHN0b3B3YXRjaEFjdGlvbjphY3Rpb24gc3RvcHdhdGNoCiAgICBjbG9jazoKICAgICAgLSAkY2xvY2tBY3Rpb246YWN0aW9uIChtZSkgKHRoZSkgY2xvY2sKICAgICAgLSAkY2xvY2tBY3Rpb246YWN0aW9uIChtZSkgKHRoZSkgdGltZQogICAgc2V0VGltZXI6CiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGVzIFttaW51dGUsIG1pbnV0ZXNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICAgIC0gc2V0IChhKSB0aW1lciBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VycyBbaG91ciwgaG91cnNdIChhbmQpCiAgICAgICAgJHB2LlR3b0RpZ2l0SW50ZWdlcjpzZWNvbmRzIFtzZWNvbmQsIHNlY29uZHNdCiAgICBzZXRBbGFybToKICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VyICRwdi5Ud29EaWdpdEludGVnZXI6bWludXRlCiAgICAgICAgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkZGF5OmRheSAoYXQpICRwdi5Ud29EaWdpdEludGVnZXI6aG91cgogICAgICAgICRwdi5Ud29EaWdpdEludGVnZXI6bWludXRlICRhbVBtOmFtUG0KICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJGRheTpkYXkgKGF0KSAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJGFtUG06YW1QbQogICAgICAtIHNldCAoYW4pIGFsYXJtIGZvciAkcHYuVHdvRGlnaXRJbnRlZ2VyOmhvdXIgJHB2LlR3b0RpZ2l0SW50ZWdlcjptaW51dGUKICAgICAgICAkYW1QbTphbVBtIChvbikgJGRheTpkYXkKICAgICAgLSBzZXQgKGFuKSBhbGFybSBmb3IgJHB2LlR3b0RpZ2l0SW50ZWdlcjpob3VyICRhbVBtOmFtUG0gKG9uKSAkZGF5OmRheQogICAgYWxhcm06CiAgICAgIC0gJGFsYXJtQWN0aW9uOmFjdGlvbiBhbGFybQogICAgYXZhaWxhYmxlQ29tbWFuZHM6CiAgICAgIC0gd2hhdCBjYW4gSSBzYXkKICBzbG90czoKICAgIHRpbWVyQWN0aW9uOgogICAgICAtIHN0YXJ0CiAgICAgIC0gcGF1c2UKICAgICAgLSBzdG9wCiAgICAgIC0gcmVzZXQKICAgICAgLSBzaG93CiAgICAgIC0gcmVzdGFydAogICAgICAtIGNsZWFyCiAgICBjbG9ja0FjdGlvbjoKICAgICAgLSBzaG93CiAgICBzdG9wd2F0Y2hBY3Rpb246CiAgICAgIC0gc3RhcnQKICAgICAgLSBzdG9wCiAgICAgIC0gcGF1c2UKICAgICAgLSByZXNldAogICAgICAtIHJlc3RhcnQKICAgICAgLSBzaG93CiAgICBhbVBtOgogICAgICAtIGEgbQogICAgICAtIHAgbQogICAgZGF5OgogICAgICAtIHRvZGF5CiAgICAgIC0gdG9tb3Jyb3cKICAgICAgLSBtb25kYXkKICAgICAgLSB0dWVzZGF5CiAgICAgIC0gd2VkbmVzZGF5CiAgICAgIC0gdGh1cnNkYXkKICAgICAgLSBmcmlkYXkKICAgICAgLSBzYXR1cmRheQogICAgICAtIHN1bmRheQogICAgYWxhcm1BY3Rpb246CiAgICAgIC0gZGVsZXRlCgAAjwAAAAAAAAACAAAABgAAAAwAAAAPAAAAEwAAABYAAAAaAAAAIAAAACYAAAAtAAAAMwAAADwAAABDAAAAUAAAAFwAAABoAAAAdAAAAH8AAACMAAAAlwAAAKQAAACvAAAAtgAAAL4AAADEAAAA0AAAANsAAADmAAAA8QAAAPsAAAAHAQAAEQEAAB0BAAAnAQAALAEAADABAAA2AQAAQgEAAE0BAABYAQAAYwEAAG0BAAB5AQAAgwEAAI8BAACZAQAAngEAAKcBAACuAQAAswEAALkBAAC7AQAAvgEAAMUBAADNAQAA1AEAANkBAADiAQAA6QEAAPYBAAACAgAADgIAABoCAAAlAgAAMgIAAD0CAABKAgAAVQIAAFgCAABcAgAAYAIAAGYCAABsAgAAdAIAAH0CAACBAgAAiAIAAJACAACUAgAAmgIAAKQCAACsAgAAugIAAMcCAADUAgAA4QIAAO0CAAD7AgAABwMAABUDAAAhAwAAJgMAACoDAAAyAwAAOAMAAEQDAABPAwAAWgMAAGUDAABvAwAAewMAAIUDAACRAwAAmwMAAKEDAACmAwAAsAMAALcDAAC7AwAAvwMAAMgDAADPAwAA3AMAAOgDAAD0AwAAAAQAAAsEAAAYBAAAIwQAADAEAAA7BAAAQQQAAEoEAABPBAAAVQQAAFsEAABkBAAAbAQAAHMEAAB6BAAAhwQAAJMEAACfBAAAqwQAALYEAADDBAAAzgQAANsEAADmBAAA6gQAAPQEAAD5BAAA/gQAAGEAYSBtAGFsYXJtAGFuAGFuZABhdABjYW4AY2xlYXIAY2xvY2sAZGVsZXRlAGVpZ2h0AGVpZ2h0ZWVuAGVpZ2h0eQBlaWdodHkgZWlnaHQAZWlnaHR5IGZpdmUAZWlnaHR5IGZvdXIAZWlnaHR5IG5pbmUAZWlnaHR5IG9uZQBlaWdodHkgc2V2ZW4AZWlnaHR5IHNpeABlaWdodHkgdGhyZWUAZWlnaHR5IHR3bwBlbGV2ZW4AZmlmdGVlbgBmaWZ0eQBmaWZ0eSBlaWdodABmaWZ0eSBmaXZlAGZpZnR5IGZvdXIAZmlmdHkgbmluZQBmaWZ0eSBvbmUAZmlmdHkgc2V2ZW4AZmlmdHkgc2l4AGZpZnR5IHRocmVlAGZpZnR5IHR3bwBmaXZlAGZvcgBmb3J0eQBmb3J0eSBlaWdodABmb3J0eSBmaXZlAGZvcnR5IGZvdXIAZm9ydHkgbmluZQBmb3J0eSBvbmUAZm9ydHkgc2V2ZW4AZm9ydHkgc2l4AGZvcnR5IHRocmVlAGZvcnR5IHR3bwBmb3VyAGZvdXJ0ZWVuAGZyaWRheQBob3VyAGhvdXJzAGkAbWUAbWludXRlAG1pbnV0ZXMAbW9uZGF5AG5pbmUAbmluZXRlZW4AbmluZXR5AG5pbmV0eSBlaWdodABuaW5ldHkgZml2ZQBuaW5ldHkgZm91cgBuaW5ldHkgbmluZQBuaW5ldHkgb25lAG5pbmV0eSBzZXZlbgBuaW5ldHkgc2l4AG5pbmV0eSB0aHJlZQBuaW5ldHkgdHdvAG9uAG9uZQBwIG0AcGF1c2UAcmVzZXQAcmVzdGFydABzYXR1cmRheQBzYXkAc2Vjb25kAHNlY29uZHMAc2V0AHNldmVuAHNldmVudGVlbgBzZXZlbnR5AHNldmVudHkgZWlnaHQAc2V2ZW50eSBmaXZlAHNldmVudHkgZm91cgBzZXZlbnR5IG5pbmUAc2V2ZW50eSBvbmUAc2V2ZW50eSBzZXZlbgBzZXZlbnR5IHNpeABzZXZlbnR5IHRocmVlAHNldmVudHkgdHdvAHNob3cAc2l4AHNpeHRlZW4Ac2l4dHkAc2l4dHkgZWlnaHQAc2l4dHkgZml2ZQBzaXh0eSBmb3VyAHNpeHR5IG5pbmUAc2l4dHkgb25lAHNpeHR5IHNldmVuAHNpeHR5IHNpeABzaXh0eSB0aHJlZQBzaXh0eSB0d28Ac3RhcnQAc3RvcABzdG9wd2F0Y2gAc3VuZGF5AHRlbgB0aGUAdGhpcnRlZW4AdGhpcnR5AHRoaXJ0eSBlaWdodAB0aGlydHkgZml2ZQB0aGlydHkgZm91cgB0aGlydHkgbmluZQB0aGlydHkgb25lAHRoaXJ0eSBzZXZlbgB0aGlydHkgc2l4AHRoaXJ0eSB0aHJlZQB0aGlydHkgdHdvAHRocmVlAHRodXJzZGF5AHRpbWUAdGltZXIAdG9kYXkAdG9tb3Jyb3cAdHVlc2RheQB0d2VsdmUAdHdlbnR5AHR3ZW50eSBlaWdodAB0d2VudHkgZml2ZQB0d2VudHkgZm91cgB0d2VudHkgbmluZQB0d2VudHkgb25lAHR3ZW50eSBzZXZlbgB0d2VudHkgc2l4AHR3ZW50eSB0aHJlZQB0d2VudHkgdHdvAHR3bwB3ZWRuZXNkYXkAd2hhdAB6ZXJvAAAAAAAAAAIAAAAEAAAABQAAAAcAAAAJAAAACgAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAGAAAABkAAAAaAAAAGwAAABwAAAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAAJgAAACcAAAAoAAAAKQAAACoAAAArAAAALgAAAC8AAAAwAAAAMQAAADIAAAAzAAAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAAOwAAAD0AAAA/AAAAQQAAAEIAAABDAAAARgAAAEcAAABJAAAASgAAAEsAAABMAAAATQAAAE4AAABPAAAAUAAAAFIAAABTAAAAVAAAAFUAAABWAAAAWAAAAFoAAABbAAAAXAAAAF0AAABeAAAAYAAAAGEAAABjAAAAZQAAAGYAAABnAAAAaAAAAGoAAABsAAAAbgAAAHAAAAByAAAAdgAAAHgAAAB6AAAAfAAAAH4AAAB/AAAAgAAAAIEAAACCAAAAgwAAAIQAAACFAAAAhgAAAIgAAACJAAAAigAAAIsAAACMAAAAjQAAAI4AAACPAAAAkQAAAJIAAACUAAAAlQAAAJcAAACZAAAAmwAAAJ0AAACfAAAAowAAAKUAAACnAAAAqQAAAKsAAACsAAAArgAAAK8AAACwAAAAsgAAALQAAAC3AAAAuAAAALoAAAC8AAAAvgAAAMAAAADCAAAAxgAAAMgAAADKAAAAzAAAAM4AAADPAAAA0QAAANMAAADVAAAAAAAAAAEAAAACAAAABQAAAAgAAAANAAAADwAAABEAAAAUAAAAFwAAABkAAAAcAAAAHwAAACMAAAAnAAAALAAAAC4AAAAyAAAANQAAADoAAABAAAAARgAAAEwAAABSAAAAWQAAAGEAAABoAAAAbgAAAHMAAAB5AAAAfwAAAIUAAACKAAAAkQAAAJkAAAChAAAAqQAAALEAAAC6AAAAxAAAAM0AAADVAAAA3AAAAN8AAADiAAAA5AAAAOcAAADsAAAA8wAAAPsAAAADAQAACwEAABMBAAAcAQAAJgEAAC8BAAA3AQAAPgEAAEEBAABHAQAATAEAAFEBAABTAQAAVQEAAFgBAABbAQAAXAEAAF4BAABjAQAAaAEAAG4BAAB0AQAAeQEAAH4BAACBAQAAhwEAAIwBAACTAQAAmwEAAKMBAACrAQAAswEAALwBAADGAQAAzwEAANcBAADeAQAA4AEAAOIBAADlAQAA6QEAAO0BAADwAQAA9QEAAPwBAAACAgAACAIAAAoCAAAQAgAAFQIAABwCAAAiAgAAJQIAACoCAAAyAgAAOQIAAD8CAABIAgAAUAIAAFoCAABjAgAAbQIAAHYCAACAAgAAiQIAAJMCAACeAgAApwIAALECAAC9AgAAyAIAANMCAADdAgAA5wIAAPACAAD5AgAAAQMAAAMDAAAHAwAADgMAABQDAAAcAwAAJQMAAC4DAAA3AwAAQAMAAEoDAABVAwAAXwMAAGgDAABwAwAAdQMAAHkDAACAAwAAhQMAAIoDAACNAwAAjwMAAJEDAACWAwAAmgMAAJ4DAACkAwAAqgMAALEDAAC4AwAAvwMAAMYDAADNAwAA1AMAANsDAADjAwAA6gMAAPIDAAD7AwAABAQAAAwEAAAUBAAAGwQAACIEAAAoBAAALgQAADEEAAA2BAAAOwQAAD4EAABCBAAARgQAAEoEAABQBAAAVgQAAFsEAABgBAAAZgQAAGsEAABxBAAAdgQAAH4EAACFBAAAjgQAAJYEAACfBAAApwQAALAEAAC4BAAAwQQAAMsEAADTBAAA3AQAAOcEAADxBAAA+wQAAAQFAAANBQAAFQUAAB0FAAAkBQAAJgUAACwFAAAyBQAANQUAADkFAAA9BQAAQQUAAAMNAwsWDQsWAxUBHBYCFwMXAxcJAhcJAh8UAhcUAxcUFREcFBUBFAkRFRIfDR8NHxIXDR8SDR8SDR8NHxIOBiMNHxIOBBwNHxIXBhcNHxIkAxcNHxIQJAMXDR8SHQsjAxcNHxIdERQdDR8SIBwSDR8SHyIRFQsjAxcSFQsjAxcOEQ4fEhcOEQ4fEg4RDh8SDR8OEQ4fEg4GIw4RDh8SDgQcDhEOHxIXBhcOEQ4fEiQDFw4RDh8SECQDFw4RDh8SHQsjAxcOEQ4fEh0RFB0OEQ4fEiAcEg4RDh8SHyIOBiMOBBwODA4cDA4EHB8SDgQcHxINHw4EHB8SDgYjDgQcHxIOBBwOBBwfEhcGFw4EHB8SJAMXDgQcHxIQJAMXDgQcHxIdCyMDFw4EHB8SHREUHQ4EHB8SIBwSDgQcHxIfIg4EHA4EHB8SFw4cBgkSDhwGCQ0FDAUcBQwmBRwmBhYSFhEXAx8WBhciHxYGFyUiHxYRFwMfHRYDFwkSFgMXCQ0XBhcXBhcfEhcXBhcfEhcGFx8SDR8XBhcfEg4GIxcGFx8SDgQcFwYXHxIXBhcXBhcfEiQDFxcGFx8SECQDFxcGFx8SHQsjAxcXBhcfEh0RFB0XBhcfEiAcEhcGFx8SHyIBFwQXJAMXECQDFxsSCxYbBCYcEh0LHxwSHR8BHB8dAh8MCRIdAh8RCQ0dDR0LFAMXCR0LFAMXHQsUAxcJJh0LFAMXJh0LHx0LIwMXHQsjAxcfEhcdCyMDFx8SHQsjAxcSHQsjAxcfEg0fHQsjAxcSDR8dCyMDFx8SDgYjHQsjAxcSDgYjHQsjAxcfEg4EHB0LIwMXEg4EHB0LIwMXHxIXBhcdCyMDFxIXBhcdCyMDFx8SJAMXHQsjAxcfEhAkAxcdCyMDFxIkAxcdCyMDFxIQJAMXHQsjAxcfEh0LIwMXHQsjAxcSHQsjAxcdCyMDFx8SHREUHR0LIwMXEh0RFB0dCyMDFx8SIBwSHQsjAxcSIBwSHQsjAxcfEh8iHQsjAxcSHyIeGR0RFB0dERQdHxIXHREUHR8SHREUHR8SDR8dERQdHxIOBiMdERQdHxIOBBwdERQdHxIXBhcdERQdHxIkAxcdERQdHxIQJAMXHREUHR8SHQsjAxcdERQdHxIdERQdHREUHR8SIBwSHREUHR8SHyIdHwEcHx0fARsdHwEbJAEIHQMXCQ0dAxcJEh8LFwoDChIgDB8SFyAMCRIgDB8SIAwJEg0fIAwfEg0fIAwJEg4GIyAMHxIOBiMgDAkSDgQcIAwfEg4EHCAMCRIXBhcgDB8SFwYXIAwJEiQDFyAMCRIQJAMXIAwfEiQDFyAMHxIQJAMXIAwJEh0LIwMXIAwfEh0LIwMXIAwJEh0RFB0gDB8SHREUHSAMCRIgHBIgDB8SIBwSIAwJEh8iIAwfEh8iIBwSIAwmCQ0gDCYJEh8GFh8GFgwfAwkNHyIJDR8DFgEcGR8iFgEcGR8iJgkSHyImCQ0fJSImCQ0fJAsVIx8kCxcfEh8kCxcSHyQLFx8SDR8fJAsXEg0fHyQLFx8SDgYjHyQLFxIOBiMfJAsXHxIOBBwfJAsXEg4EHB8kCxcfEhcGFx8kCxcSFwYXHyQLFx8SJAMXHyQLFx8SECQDFx8kCxcSJAMXHyQLFxIQJAMXHyQLFx8SHQsjAxcfJAsXEh0LIwMXHyQLFx8SHREUHR8kCxcSHREUHR8kCxcfEiAcEh8kCxcSIBwSHyQLFx8SHyIfJAsXEh8iHyIkCxcmCRIkCxcmCQ0kAx8QJAMfJhEcGSYSHBkAAAAgAAAAAAAAAAEAAAADAAAABAAAAA0AAABxAAAA1QAAADkBAACdAQAAAQIAAAcCAAAOAgAAEAIAABICAAAUAgAAFQIAABYCAAAXAgAAGAIAABkCAAAaAgAAGwIAABwCAAAdAgAAHgIAAB8CAAAgAgAAIQIAACICAAAjAgAAJAIAACUCAAAmAgAACQAAAAEAAABGAAAAWwAAAH0AAAB+AAAANwAAAH8AAACMAAAAegAAADAAAABKAAAAawAAAI4AAABFAAAAiwAAAHkAAAAuAAAAIgAAAFwAAABPAAAACgAAADgAAABsAAAAFgAAAIAAAABuAAAALwAAABcAAABdAAAAUAAAAAsAAAA5AAAAgQAAAIYAAACKAAAAiQAAAIQAAACDAAAAiAAAAIcAAACCAAAAhQAAAG8AAAB0AAAAeAAAAHcAAAByAAAAcQAAAHYAAAB1AAAAcAAAAHMAAAAkAAAAKQAAAC0AAAAsAAAAJwAAACYAAAArAAAAKgAAACUAAAAoAAAAGAAAAB0AAAAhAAAAIAAAABsAAAAaAAAAHwAAAB4AAAAZAAAAHAAAAF4AAABjAAAAZwAAAGYAAABhAAAAYAAAAGUAAABkAAAAXwAAAGIAAABRAAAAVgAAAFoAAABZAAAAVAAAAFMAAABYAAAAVwAAAFIAAABVAAAADAAAABEAAAAVAAAAFAAAAA8AAAAOAAAAEwAAABIAAAANAAAAEAAAADoAAAA/AAAAQwAAAEIAAAA9AAAAPAAAAEEAAABAAAAAOwAAAD4AAACOAAAARQAAAIsAAAB5AAAALgAAACIAAABcAAAATwAAAAoAAAA4AAAAbAAAABYAAACAAAAAbgAAAC8AAAAXAAAAXQAAAFAAAAALAAAAOQAAAIEAAACGAAAAigAAAIkAAACEAAAAgwAAAIgAAACHAAAAggAAAIUAAABvAAAAdAAAAHgAAAB3AAAAcgAAAHEAAAB2AAAAdQAAAHAAAABzAAAAJAAAACkAAAAtAAAALAAAACcAAAAmAAAAKwAAACoAAAAlAAAAKAAAABgAAAAdAAAAIQAAACAAAAAbAAAAGgAAAB8AAAAeAAAAGQAAABwAAABeAAAAYwAAAGcAAABmAAAAYQAAAGAAAABlAAAAZAAAAF8AAABiAAAAUQAAAFYAAABaAAAAWQAAAFQAAABTAAAAWAAAAFcAAABSAAAAVQAAAAwAAAARAAAAFQAAABQAAAAPAAAADgAAABMAAAASAAAADQAAABAAAAA6AAAAPwAAAEMAAABCAAAAPQAAADwAAABBAAAAQAAAADsAAAA+AAAAjgAAAEUAAACLAAAAeQAAAC4AAAAiAAAAXAAAAE8AAAAKAAAAOAAAAGwAAAAWAAAAgAAAAG4AAAAvAAAAFwAAAF0AAABQAAAACwAAADkAAACBAAAAhgAAAIoAAACJAAAAhAAAAIMAAACIAAAAhwAAAIIAAACFAAAAbwAAAHQAAAB4AAAAdwAAAHIAAABxAAAAdgAAAHUAAABwAAAAcwAAACQAAAApAAAALQAAACwAAAAnAAAAJgAAACsAAAAqAAAAJQAAACgAAAAYAAAAHQAAACEAAAAgAAAAGwAAABoAAAAfAAAAHgAAABkAAAAcAAAAXgAAAGMAAABnAAAAZgAAAGEAAABgAAAAZQAAAGQAAABfAAAAYgAAAFEAAABWAAAAWgAAAFkAAABUAAAAUwAAAFgAAABXAAAAUgAAAFUAAAAMAAAAEQAAABUAAAAUAAAADwAAAA4AAAATAAAAEgAAAA0AAAAQAAAAOgAAAD8AAABDAAAAQgAAAD0AAAA8AAAAQQAAAEAAAAA7AAAAPgAAAI4AAABFAAAAiwAAAHkAAAAuAAAAIgAAAFwAAABPAAAACgAAADgAAABsAAAAFgAAAIAAAABuAAAALwAAABcAAABdAAAAUAAAAAsAAAA5AAAAgQAAAIYAAACKAAAAiQAAAIQAAACDAAAAiAAAAIcAAACCAAAAhQAAAG8AAAB0AAAAeAAAAHcAAAByAAAAcQAAAHYAAAB1AAAAcAAAAHMAAAAkAAAAKQAAAC0AAAAsAAAAJwAAACYAAAArAAAAKgAAACUAAAAoAAAAGAAAAB0AAAAhAAAAIAAAABsAAAAaAAAAHwAAAB4AAAAZAAAAHAAAAF4AAABjAAAAZwAAAGYAAABhAAAAYAAAAGUAAABkAAAAXwAAAGIAAABRAAAAVgAAAFoAAABZAAAAVAAAAFMAAABYAAAAVwAAAFIAAABVAAAADAAAABEAAAAVAAAAFAAAAA8AAAAOAAAAEwAAABIAAAANAAAAEAAAADoAAAA/AAAAQwAAAEIAAAA9AAAAPAAAAEEAAABAAAAAOwAAAD4AAACOAAAARQAAAIsAAAB5AAAALgAAACIAAABcAAAATwAAAAoAAAA4AAAAbAAAABYAAACAAAAAbgAAAC8AAAAXAAAAXQAAAFAAAAALAAAAOQAAAIEAAACGAAAAigAAAIkAAACEAAAAgwAAAIgAAACHAAAAggAAAIUAAABvAAAAdAAAAHgAAAB3AAAAcgAAAHEAAAB2AAAAdQAAAHAAAABzAAAAJAAAACkAAAAtAAAALAAAACcAAAAmAAAAKwAAACoAAAAlAAAAKAAAABgAAAAdAAAAIQAAACAAAAAbAAAAGgAAAB8AAAAeAAAAGQAAABwAAABeAAAAYwAAAGcAAABmAAAAYQAAAGAAAABlAAAAZAAAAF8AAABiAAAAUQAAAFYAAABaAAAAWQAAAFQAAABTAAAAWAAAAFcAAABSAAAAVQAAAAwAAAARAAAAFQAAABQAAAAPAAAADgAAABMAAAASAAAADQAAABAAAAA6AAAAPwAAAEMAAABCAAAAPQAAADwAAABBAAAAQAAAADsAAAA+AAAAaAAAAGkAAABHAAAASAAAAEkAAABbAAAAaAAAAEcAAABpAAAASAAAAFsAAABJAAAABwAAADEAAAAyAAAANQAAADYAAABMAAAATQAAAAAAAAACAAAAAwAAAAQAAAAFAAAABgAAAAgAAAAjAAAAMwAAADQAAABEAAAASwAAAE4AAABqAAAAbQAAAHsAAAB8AAAAjQAAAAAAAAAMAAAAEQAAAB0AAAAhAAAANAAAAEcAAABaAAAAbQAAAIAAAACQAAAAnAAAAJ0AAACeAAAAnwAAAKAAAAChAAAAogAAAKMAAACkAAAApQAAAKYAAACnAAAAqAAAAKkAAACqAAAAqwAAAKwAAACtAAAArgAAAK8AAACwAAAAsQAAAGFsYXJtQWN0aW9uAGFtUG0AY2xvY2tBY3Rpb24AZGF5AHB2LlR3b0RpZ2l0SW50ZWdlcgBwdi5Ud29EaWdpdEludGVnZXIAcHYuVHdvRGlnaXRJbnRlZ2VyAHB2LlR3b0RpZ2l0SW50ZWdlcgBwdi5Ud29EaWdpdEludGVnZXIAc3RvcHdhdGNoQWN0aW9uAHRpbWVyQWN0aW9uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAADAAAABMAAAAXAAAAHAAAACIAAAApAAAAMQAAADkAAABAAAAARwAAAEgAAABJAAAASgAAAEsAAABMAAAATQAAAE4AAABPAAAAUAAAAFEAAABSAAAAUwAAAFQAAABVAAAAVgAAAFcAAABYAAAAWQAAAFoAAABbAAAAXAAAAGFjdGlvbgBhbVBtAGFjdGlvbgBkYXkAaG91cgBob3VycwBtaW51dGUAbWludXRlcwBzZWNvbmRzAGFjdGlvbgBhY3Rpb24AAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAGAAAAGAAAAB4AAAAnAAAAMAAAADoAAABAAAAAYWxhcm0AYXZhaWxhYmxlQ29tbWFuZHMAY2xvY2sAc2V0QWxhcm0Ac2V0VGltZXIAc3RvcHdhdGNoAHRpbWVyAAQAAAAAAAAA//////////8GAAAAKAAAAEwAAABwAAAAXAEAAAQKAAAoCgAAAAAAAAoAAAD/////AQAAADwAAAAoAAAAHgAAAAYAAAAAAAAAAAAAAAkAAAD/////AQAAAGAAAABMAAAAGwAAAAUAAAAAAAAAAAAAAAIAAAD/////BAAAAJAAAAAEAQAAPAEAAEwBAABwAAAAFwAAAP////8DAAAArAAAAOQAAAD0AAAAkAAAABwAAAD/////AgAAAMQAAADUAAAArAAAABQAAAACAAAAAAAAAKwAAAAdAAAAAgAAAAAAAACQAAAAFAAAAAIAAAAAAAAAkAAAAB0AAAACAAAAAAAAAHAAAAAcAAAA/////wIAAAAcAQAALAEAAAQBAAAUAAAAAgAAAAAAAAAEAQAAHQAAAAIAAAAAAAAAcAAAABQAAAACAAAAAAAAAHAAAAAdAAAAAgAAAAAAAAAAAAAAGgAAAP////8EAAAAfAEAAAwEAACIBgAAUAgAAFwBAAAOAAAA/////wEAAACQAQAAfAEAAB4AAAD/////AQAAAKQBAACQAQAAFQAAAP////8DAAAAwAEAAGADAADoAwAApAEAAAUAAAD/////AQAAANQBAADAAQAACwAAAAQAAAADAAAA8AEAALQCAAA8AwAA1AEAABEAAAD/////AgAAAAgCAACQAgAA8AEAAAcAAAD/////AQAAABwCAAAIAgAADAAAAAQAAAACAAAANAIAAGwCAAAcAgAAEQAAAP////8BAAAASAIAADQCAAAIAAAA/////wEAAABcAgAASAIAAA0AAAAEAAAAAAAAABwCAAAIAAAA/////wEAAACAAgAAbAIAAA0AAAAEAAAAAAAAAPABAAAIAAAA/////wEAAACkAgAAkAIAAA0AAAAEAAAAAAAAANQBAAAHAAAA/////wEAAADIAgAAtAIAAAwAAAAEAAAAAgAAAOACAAAYAwAAyAIAABEAAAD/////AQAAAPQCAADgAgAACAAAAP////8BAAAACAMAAPQCAAANAAAABAAAAAAAAADIAgAACAAAAP////8BAAAALAMAABgDAAANAAAABAAAAAAAAADUAQAACAAAAP////8BAAAAUAMAADwDAAANAAAABAAAAAAAAACkAQAABwAAAP////8BAAAAdAMAAGADAAAMAAAABAAAAAIAAACMAwAAxAMAAHQDAAARAAAA/////wEAAACgAwAAjAMAAAgAAAD/////AQAAALQDAACgAwAADQAAAAQAAAAAAAAAdAMAAAgAAAD/////AQAAANgDAADEAwAADQAAAAQAAAAAAAAApAEAAAgAAAD/////AQAAAPwDAADoAwAADQAAAAQAAAAAAAAAXAEAAB4AAAD/////AQAAACAEAAAMBAAAFQAAAP////8DAAAAPAQAANwFAABkBgAAIAQAAAUAAAD/////AQAAAFAEAAA8BAAACwAAAAQAAAADAAAAbAQAADAFAAC4BQAAUAQAABEAAAD/////AgAAAIQEAAAMBQAAbAQAAAcAAAD/////AQAAAJgEAACEBAAADAAAAAQAAAACAAAAsAQAAOgEAACYBAAAEQAAAP////8BAAAAxAQAALAEAAAIAAAA/////wEAAADYBAAAxAQAAA0AAAAEAAAAAAAAAJgEAAAIAAAA/////wEAAAD8BAAA6AQAAA0AAAAEAAAAAAAAAGwEAAAIAAAA/////wEAAAAgBQAADAUAAA0AAAAEAAAAAAAAAFAEAAAHAAAA/////wEAAABEBQAAMAUAAAwAAAAEAAAAAgAAAFwFAACUBQAARAUAABEAAAD/////AQAAAHAFAABcBQAACAAAAP////8BAAAAhAUAAHAFAAANAAAABAAAAAAAAABEBQAACAAAAP////8BAAAAqAUAAJQFAAANAAAABAAAAAAAAABQBAAACAAAAP////8BAAAAzAUAALgFAAANAAAABAAAAAAAAAAgBAAABwAAAP////8BAAAA8AUAANwFAAAMAAAABAAAAAIAAAAIBgAAQAYAAPAFAAARAAAA/////wEAAAAcBgAACAYAAAgAAAD/////AQAAADAGAAAcBgAADQAAAAQAAAAAAAAA8AUAAAgAAAD/////AQAAAFQGAABABgAADQAAAAQAAAAAAAAAIAQAAAgAAAD/////AQAAAHgGAABkBgAADQAAAAQAAAAAAAAAXAEAABAAAAD/////AQAAAJwGAACIBgAADwAAAP////8BAAAAsAYAAJwGAAAVAAAA/////wIAAADIBgAAjAcAALAGAAAEAAAA/////wIAAADgBgAAQAcAAMgGAAAGAAAA/////wEAAAD0BgAA4AYAAAEAAAADAAAAAgAAAAwHAAAwBwAA9AYAABgAAAD/////AQAAACAHAAAMBwAAAwAAAAMAAAAAAAAA9AYAAAMAAAADAAAAAAAAAMgGAAABAAAAAwAAAAIAAABYBwAAfAcAAEAHAAAYAAAA/////wEAAABsBwAAWAcAAAMAAAADAAAAAAAAAEAHAAADAAAAAwAAAAAAAACwBgAAAwAAAP////8CAAAApAcAAAQIAACMBwAAEgAAAP////8BAAAAuAcAAKQHAAAEAAAA/////wIAAADQBwAA9AcAALgHAAAGAAAA/////wEAAADkBwAA0AcAAAEAAAADAAAAAAAAALgHAAABAAAAAwAAAAAAAACMBwAABAAAAP////8CAAAAHAgAAEAIAAAECAAABgAAAP////8BAAAAMAgAABwIAAABAAAAAwAAAAAAAAAECAAAAQAAAAMAAAAAAAAAXAEAAA8AAAD/////AQAAAGQIAABQCAAAFQAAAP////8CAAAAfAgAAEAJAABkCAAABAAAAP////8CAAAAlAgAAPQIAAB8CAAABgAAAP////8BAAAAqAgAAJQIAAABAAAAAwAAAAIAAADACAAA5AgAAKgIAAAYAAAA/////wEAAADUCAAAwAgAAAMAAAADAAAAAAAAAKgIAAADAAAAAwAAAAAAAAB8CAAAAQAAAAMAAAACAAAADAkAADAJAAD0CAAAGAAAAP////8BAAAAIAkAAAwJAAADAAAAAwAAAAAAAAD0CAAAAwAAAAMAAAAAAAAAZAgAAAMAAAD/////AgAAAFgJAAC4CQAAQAkAABIAAAD/////AQAAAGwJAABYCQAABAAAAP////8CAAAAhAkAAKgJAABsCQAABgAAAP////8BAAAAmAkAAIQJAAABAAAAAwAAAAAAAABsCQAAAQAAAAMAAAAAAAAAQAkAAAQAAAD/////AgAAANAJAAD0CQAAuAkAAAYAAAD/////AQAAAOQJAADQCQAAAQAAAAMAAAAAAAAAuAkAAAEAAAADAAAAAAAAAAAAAAAAAAAA/////wEAAAAYCgAABAoAAA8AAAAAAAAAAAAAAAAAAAAfAAAA/////wEAAAA8CgAAKAoAABMAAAD/////AQAAAFAKAAA8CgAAFgAAAP////8BAAAAZAoAAFAKAAAZAAAAAQAAAAAAAAA=',
        },
      }"
      v-bind:picovoiceFactory="factory"
      v-on:pv-init="pvInitFn"
      v-on:pv-ready="pvReadyFn"
      v-on:ppn-keyword="pvKeywordFn"
      v-on:rhn-inference="pvInferenceFn"
      v-on:pv-error="pvErrorFn"
    />
    <h2>VoiceWidget</h2>
    <h3>Loaded: {{ isLoaded }}</h3>
    <h3>Listening: {{ isListening }}</h3>
    <h3>Engine: {{ engine }}</h3>
    <h3>Error: {{ isError }}</h3>
    <p class="error-message" v-if="isError">
      {{ JSON.stringify(errorMessage) }}
    </p>
    <button v-on:click="start" :disabled="!isLoaded || isError || isListening">
      Start
    </button>
    <button v-on:click="pause" :disabled="!isLoaded || isError || !isListening">
      Pause
    </button>
    <button v-on:click="resume" :disabled="!isLoaded || isError || isListening">
      Resume
    </button>
    <h3>Keyword Detections (Listening for "Picovoice")</h3>
    {{ detections }}
    <h3>Inference: (Follow-on commands in "Clock" context)</h3>
    <code v-if="inference !== null">
      {{ inference }}
    </code>
  </div>
</template>

<script>
import Picovoice from "@picovoice/picovoice-web-vue";
import { PicovoiceWorkerFactory as PicovoiceWorkerFactoryEn } from "@picovoice/picovoice-web-en-worker";

export default {
  name: "VoiceWidget",
  components: {
    Picovoice,
  },
  data: function () {
    return {
      inference: null,
      detections: [],
      isError: false,
      isLoaded: false,
      isListening: false,
      isTalking: false,
      engine: null,
      factory: PicovoiceWorkerFactoryEn,
    };
  },
  methods: {
    start: function () {
      if (this.$refs.picovoice.start()) {
        this.isListening = !this.isListening;
      }
    },
    pause: function () {
      if (this.$refs.picovoice.pause()) {
        this.isListening = !this.isListening;
      }
    },
    resume: function () {
      if (this.$refs.picovoice.resume()) {
        this.isListening = !this.isListening;
      }
    },

    pvInitFn: function () {
      this.isError = false;
    },
    pvReadyFn: function () {
      this.isLoaded = true;
      this.isListening = true;
      this.engine = 'ppn'
    },
    pvKeywordFn: function (keyword) {
      this.detections = [...this.detections, keyword];
      this.engine = 'rhn'
    },
    pvInferenceFn: function (inference) {
      this.inference = inference;
      this.engine = 'ppn'
    },
    pvErrorFn: function (error) {
      this.isError = true;
      this.errorMessage = error.toString();
    },
  },
};
</script>

<style scoped>
button {
  padding: 1rem;
  font-size: 1.5rem;
  margin-right: 1rem;
}

.voice-widget {
  border: 2px double #377dff;
  padding: 2rem;
}

.error-message {
  background-color: maroon;
  color: white;
  padding: 1rem;
  border-left: 5px solid red;
  font-family: monospace;
  font-weight: bold;
  font-size: 1.5rem;
}
</style>
